-- 2. Seasonal trends for top three items

SELECT
		PRODUCTCODE,
		MONTH(ORDERDATE) AS Sales_Month,
		SUM(QUANTITYORDERED) AS Total_Quantity
FROM SalesData
WHERE PRODUCTCODE IN 
					(SELECT TOP 3 PRODUCTCODE FROM SalesData GROUP BY PRODUCTCODE ORDER BY SUM(QUANTITYORDERED) DESC)
GROUP BY PRODUCTCODE, MONTH(ORDERDATE)
ORDER BY PRODUCTCODE, Sales_Month;