-- Create the Database
CREATE DATABASE SalesPerformanceTracker;
GO

-- Switch to the new database
USE SalesPerformanceTracker;
GO

-- Create the Table
CREATE TABLE SalesData (
    [ORDERNUMBER] INT,
    [QUANTITYORDERED] INT,
    [PRICEEACH] FLOAT,
    [ORDERLINENUMBER] INT,
    [SALES] FLOAT,
    [ORDERDATE] DATETIME,
    [STATUS] VARCHAR(50),
    [QTR_ID] INT,
    [MONTH_ID] INT,
    [YEAR_ID] INT,
    [PRODUCTLINE] VARCHAR(100),
    [MSRP] FLOAT,
    [PRODUCTCODE] VARCHAR(50),
    [CUSTOMERNAME] VARCHAR(150),
    [PHONE] VARCHAR(50),
    [ADDRESSLINE] VARCHAR(255),
    [CITY] VARCHAR(100),
    [STATE] VARCHAR(100),
    [POSTALCODE] VARCHAR(50),
    [COUNTRY] VARCHAR(100),
    [TERRITORY] VARCHAR(50),
    [CONTACTLASTNAME] VARCHAR(100),
    [CONTACTFIRSTNAME] VARCHAR(100),
    [DEALSIZE] VARCHAR(50)
);
GO